import { createContext, useContext, useEffect, useMemo, useState } from 'react'

const translations = {
  en: {
    'nav.dashboard': 'Dashboard',
    'nav.weekPlanner': 'Week Planner',
    'nav.projects': 'Projects',
    'nav.money': 'Money',
    'nav.notes': 'Notes',
    'nav.wishlist': 'Wishlist',
    'nav.vision': 'Vision',
    'nav.profile': 'Profile',
    'nav.logout': 'Logout',
    'profile.kicker': 'Your cozy corner',
    'profile.title': 'Profile Studio',
    'profile.subtitle': 'Shape your space, save your mood, and upload a sweet portrait.',
    'profile.mood': 'Mood',
    'profile.language': 'Language',
    'profile.fallbackName': 'Sweet Planner',
    'profile.fallbackFocus': 'Soft focus, gentle wins',
    'profile.unknownDate': 'Unknown date',
    'profile.avatarAlt': 'Profile',
    'profile.uploadPhoto': 'Upload photo',
    'profile.removePhoto': 'Remove photo',
    'profile.about': 'About you',
    'profile.displayName': 'Display name',
    'profile.focus': 'Current focus',
    'profile.bio': 'Bio',
    'profile.bioPlaceholder': 'A few dreamy lines about you...',
    'profile.mantra': 'Favorite quote / mantra',
    'profile.mantraPlaceholder': 'A soft line that keeps you going',
    'profile.birthday': 'Birthday',
    'profile.theme': 'Theme mood',
    'profile.themeStrawberry': 'Strawberry',
    'profile.themeRoseTea': 'Rose tea',
    'profile.themeVanilla': 'Vanilla',
    'profile.themeMatcha': 'Matcha',
    'profile.langEnglish': 'English',
    'profile.langFrench': 'French',
    'profile.langGerman': 'German',
    'profile.save': 'Save changes',
    'profile.saved': 'Saved!',
    'profile.stats': 'Your stats',
    'profile.updating': 'Updating...',
    'profile.statTask': 'Task',
    'profile.statGoal': 'Goal',
    'profile.statWish': 'Wish',
    'profile.statBuild': 'Build',
    'profile.tasksCompleted': 'Tasks completed',
    'profile.visionGoals': 'Vision goals',
    'profile.goalsAchieved': 'Goals achieved',
    'profile.wishlistWins': 'Wishlist wins',
    'profile.projectsCreated': 'Projects created',
    'profile.security': 'Security',
    'profile.currentPassword': 'Current password',
    'profile.newPassword': 'New password',
    'profile.confirmPassword': 'Confirm new password',
    'profile.passwordPlaceholderMin': 'At least 8 characters',
    'profile.passwordPlaceholderConfirm': 'Re-enter password',
    'profile.passwordRequired': 'Please fill out all password fields.',
    'profile.passwordTooShort': 'New password must be at least 8 characters.',
    'profile.passwordMismatch': 'New password and confirmation do not match.',
    'profile.passwordUpdated': 'Password updated!',
    'profile.passwordFailed': 'Password update failed.',
    'profile.updatePassword': 'Update password',
    'profile.logout': 'Log out',
    'profile.joined': 'Joined Rosy Workroom on',
    'profile.noteKicker': 'Today in your room',
    'profile.noteText': 'Keep it gentle. One tiny win is still a win.',
    'dashboard.welcomeTitle': 'Welcome back sweetheart to your cozy workroom',
    'dashboard.welcomeSubtitle': 'Today is about gentle focus. Pick one project, move one card, and log one win.',
    'dashboard.todayPlan': 'Today plan',
    'dashboard.moneySnapshot': 'Money snapshot',
    'dashboard.reminders': 'Reminders',
    'dashboard.noTasks': 'No tasks yet. Add your first one.',
    'dashboard.addTaskPlaceholder': 'Add a task',
    'dashboard.addTaskButton': 'Add',
    'dashboard.spent': 'Spent',
    'dashboard.saved': 'Saved',
    'dashboard.moneyTrendAria': 'Money trend',
    'dashboard.monthSpent': 'Spent',
    'dashboard.monthSaved': 'Saved',
    'dashboard.noReminders': 'No reminders yet. Add one from notes.',
    'dashboard.manageReminders': 'Manage reminders',
    'dashboard.deleteTaskTitle': 'Delete task',
    'dashboard.deleteTaskMessage': 'Are you sure you want to delete "{task}"? This action cannot be undone.',
    'dashboard.thisTask': 'this task',
    'week.title': 'Weekly Planner',
    'week.currentWeek': 'Current week',
    'week.backToCurrent': 'Back to current',
    'week.days.monday': 'Monday',
    'week.days.tuesday': 'Tuesday',
    'week.days.wednesday': 'Wednesday',
    'week.days.thursday': 'Thursday',
    'week.days.friday': 'Friday',
    'week.days.saturday': 'Saturday',
    'week.days.sunday': 'Sunday',
    'week.reflection': 'Weekly Reflection',
    'week.tasksCount': 'tasks',
    'week.history': 'History',
    'week.noPastWeeks': 'No past weeks yet.',
    'week.current': 'Current',
    'week.updated': 'Updated',
    'week.viewAllHistory': 'View all history',
    'week.doneOf': 'of',
    'week.doneLabel': 'done',
    'week.carryOver': 'Carry over',
    'week.carryOverTitle': 'Move all unfinished tasks to tomorrow',
    'week.endOfWeekSummary': 'End-of-week summary',
    'week.dailyFocusGoal': 'Daily Focus Goal',
    'week.focusPlaceholder': 'Main win for today...',
    'week.dailyTasks': 'Daily Tasks',
    'week.taskPlaceholder': 'Add a task...',
    'week.block.anytime': 'Anytime',
    'week.block.morning': 'Morning',
    'week.block.afternoon': 'Afternoon',
    'week.block.evening': 'Evening',
    'week.block.night': 'Night',
    'week.priority.high': 'High',
    'week.priority.medium': 'Medium',
    'week.priority.low': 'Low',
    'week.noTasksDay': 'No tasks yet for this day.',
    'week.reflectionTitle': 'Weekly Reflection',
    'week.reflectionWins': 'Wins',
    'week.reflectionLessons': 'Lessons',
    'week.reflectionNextWeek': 'Next Week',
    'week.reflectionWinsPlaceholder': 'What went well this week?',
    'week.reflectionLessonsPlaceholder': 'What did you learn?',
    'week.reflectionNextWeekPlaceholder': 'What do you want to focus on next week?',
    'week.notesTitle': 'Notes',
    'week.notesPlaceholder': 'Add notes for this day...',
    'week.loading': 'Loading your planner...',
    'week.deleteTaskTitle': 'Delete task',
    'week.deleteTaskMessage': 'Are you sure you want to delete "{task}"? This action cannot be undone.',
    'week.thisTask': 'this task',
    'week.addTaskButton': 'Add',
    'vision.title': 'Vision Board',
    'vision.addGoal': 'Add goal',
    'vision.addGoalTitle': 'Add Vision Goal',
    'vision.goalTitlePlaceholder': 'Goal title',
    'vision.goalDescriptionPlaceholder': 'Describe your vision...',
    'vision.goalIconPlaceholder': 'Emoji icon',
    'vision.cancel': 'Cancel',
    'vision.addGoalButton': 'Add Goal',
    'vision.deleteGoalTitle': 'Delete goal',
    'vision.deleteGoalMessage': 'Are you sure you want to delete "{goal}"? This action cannot be undone.',
    'vision.thisGoal': 'this goal',
    'vision.markAchieved': 'Mark achieved',
    'vision.markDone': 'Mark done',
    'vision.markUnachieved': 'Mark not achieved',
    'vision.moveBackToGoals': 'Move back to goals',
    'vision.achieved': 'Achieved',
    'vision.archivedTitle': 'Achieved Goals',
    'vision.archivedSubtitle': 'A sweet archive of goals you already completed.',
    'vision.emptyCategory': 'No goals in this category yet.',
    'vision.emptyArchived': 'No achieved goals yet. Keep blooming.',
    'vision.category.financial.label': 'Financial',
    'vision.category.financial.desc': 'Money management, income growth, savings, debt reduction, and long-term financial security.',
    'vision.category.business.label': 'Business',
    'vision.category.business.desc': 'Career growth, professional achievements, entrepreneurship, and business projects.',
    'vision.category.relationships.label': 'Relationships',
    'vision.category.relationships.desc': 'Meaningful connections with partner, friends, family, and the relationships you want to build.',
    'vision.category.health_fitness.label': 'Health & Fitness',
    'vision.category.health_fitness.desc': 'Physical health, fitness, healthy habits, and overall well-being.',
    'vision.category.fun_recreation.label': 'Fun & Recreation',
    'vision.category.fun_recreation.desc': 'Hobbies, travel, joy, and activities that help you recharge.',
    'vision.category.personal.label': 'Personal',
    'vision.category.personal.desc': 'Self-development, education, habits, lifestyle, and personal life improvements.',
    'vision.category.contribution.label': 'Contribution',
    'vision.category.contribution.desc': 'Giving back, helping others, volunteering, donating, and positive impact.',
    'common.cancel': 'Cancel',
    'common.delete': 'Delete',
    'common.add': 'Add',
    'common.save': 'Save',
    'common.update': 'Update',
    'common.edit': 'Edit',
    'common.back': 'Back',
    'common.loading': 'Loading...',
    'common.none': 'None',
    'login.createTitle': 'Create Account',
    'login.welcomeTitle': 'Welcome Back',
    'login.username': 'Username',
    'login.password': 'Password',
    'login.emailOptional': 'Email (optional)',
    'login.usernamePlaceholder': 'Enter username',
    'login.passwordPlaceholder': 'Enter password',
    'login.emailPlaceholder': 'Enter email',
    'login.authFailed': 'Authentication failed',
    'login.accountCreated': 'Account created! Please log in.',
    'login.pleaseWait': 'Please wait...',
    'login.signUp': 'Sign Up',
    'login.logIn': 'Log In',
    'login.haveAccount': 'Already have an account? Log In',
    'login.noAccount': "Don't have an account? Sign Up",
    'landing.headerLogin': 'Log In',
    'landing.headerGetStarted': 'Get Started',
    'landing.heroTitle': 'Rosy Workroom',
    'landing.heroSubtitle': 'A gentle workspace to plan, track, and bloom.',
    'landing.heroDescription': 'One cozy place for projects, kanban tasks, budgets, notes, goals, and weekly planning. Designed with a soft pink palette and calm focus to make progress feel lovely.',
    'landing.heroAlt': 'Strawberry girl sticker',
    'landing.heroGetStarted': 'Get Started',
    'landing.heroLogin': 'Log In',
    'landing.projectProjectsTitle': 'Projects',
    'landing.projectProjectsDesc': 'Create and organize all your projects in one place. Add tags, set due dates, and keep track of everything you are working on with a beautiful, distraction-free interface.',
    'landing.projectProjectsLink': 'View Projects',
    'landing.projectKanbanTitle': 'Kanban Board',
    'landing.projectKanbanDesc': 'Visualize your workflow with customizable kanban boards. Move tasks through To Do, In Progress, and Done columns. Add checklists and track progress with ease.',
    'landing.projectKanbanLink': 'Create Project',
    'landing.projectBudgetTitle': 'Budget Tracker',
    'landing.projectBudgetDesc': 'Manage your finances with monthly budgets and transaction tracking. Set budget goals, record expenses and income, and see exactly where your money goes each month.',
    'landing.projectBudgetLink': 'Track Budget',
    'landing.projectNotesTitle': 'Notes',
    'landing.projectNotesDesc': 'Capture thoughts, ideas, and important information in a clean notepad. Perfect for journaling, meeting notes, or keeping track of anything that matters to you.',
    'landing.projectNotesLink': 'Take Notes',
    'landing.projectVisionTitle': 'Vision Board',
    'landing.projectVisionDesc': 'Define your dreams and long-term goals. Create a vision for what you want to achieve and keep yourself inspired and motivated with clear, meaningful objectives.',
    'landing.projectVisionLink': 'Build Vision',
    'landing.projectWeekTitle': 'Weekly Planner',
    'landing.projectWeekDesc': 'Plan your week with intention. Set priorities, schedule tasks, and create weekly plans that keep you focused and organized without overwhelming you.',
    'landing.projectWeekLink': 'Plan Week',
    'landing.reviewsTitle': 'What people are saying',
    'landing.reviewsSubtitle': 'Sweet feedbacks and gentle requests help Rosy Workroom bloom.',
    'landing.reviewsBadge': '5.0 cozy Bewertung',
    'landing.review1Quote': 'The weekly planner keeps my goals soft and realistic. I love the calm layout.',
    'landing.review1Tag': 'Weekly planner',
    'landing.review2Quote': 'The kanban board feels like journaling, but with cute structure.',
    'landing.review2Tag': 'Projects + Kanban',
    'landing.review3Quote': 'Budget tracking is finally pretty. I check it every morning.',
    'landing.review3Tag': 'Money tracking',
    'landing.footerMade': 'Made with love for gentle productivity',
    'landing.footerRights': 'All rights reserved.',
    'home.title': 'Strawberry Bloom Studio',
    'home.subtitle': 'A sweet space for planning, tracking, and dreamy focus.',
    'home.description': 'Organize projects, money, notes, and goals in one cozy place. Set gentle priorities, track your wins, and keep your days soft and intentional.',
    'home.planProjects': 'Plan Your Projects',
    'home.planWeek': 'Plan Your Week',
    'home.trackMoney': 'Track Your Money',
    'home.addGoals': 'Add Your Goals',
    'home.takeNotes': 'Take Notes',
    'notes.title': 'Notes',
    'notes.newNote': 'New note',
    'notes.addNoteTitle': 'Add Note',
    'notes.noteTitlePlaceholder': 'Note title',
    'notes.noteContentPlaceholder': 'Write your note here...',
    'notes.noteTagsPlaceholder': 'Tags (comma separated)',
    'notes.empty': 'No notes yet',
    'notes.deleteTitle': 'Delete note',
    'notes.deleteMessage': 'Are you sure you want to delete "{note}"? This action cannot be undone.',
    'notes.thisNote': 'this note',
    'notes.addNoteButton': 'Add Note',
    'money.title': 'Money Tracker',
    'money.addTransaction': 'Add transaction',
    'money.addTransactionTitle': 'Add Transaction',
    'money.itemPlaceholder': 'Item',
    'money.categoryPlaceholder': 'Category',
    'money.amountPlaceholder': 'Amount',
    'money.addTransactionButton': 'Add Transaction',
    'money.setBudgetTitle': 'Set Monthly Budget',
    'money.budgetPlaceholder': 'Budget amount',
    'money.saveBudget': 'Save Budget',
    'money.monthlyOverview': 'Monthly overview',
    'money.editBudget': 'Edit budget',
    'money.budgetLabel': 'Budget',
    'money.spentLabel': 'Spent',
    'money.savedLabel': 'Saved',
    'money.topCategory': 'Top Category',
    'money.categories': 'Categories',
    'money.budgetUsed': 'of budget used',
    'money.recentTransactions': 'Recent transactions',
    'money.tableDate': 'Date',
    'money.tableItem': 'Item',
    'money.tableCategory': 'Category',
    'money.tableAmount': 'Amount',
    'money.noTransactions': 'No transactions yet',
    'money.deleteTitle': 'Delete transaction',
    'money.deleteMessage': 'Are you sure you want to delete "{tx}"? This action cannot be undone.',
    'money.thisTransaction': 'this transaction',
    'projects.title': 'Projects',
    'projects.backToProjects': 'Back to Projects',
    'projects.addProject': 'Add Project',
    'projects.createTitle': 'Create Project',
    'projects.projectName': 'Project name',
    'projects.projectNamePlaceholder': 'Project name',
    'projects.tags': 'Tags',
    'projects.tagsPlaceholder': 'Tags (comma separated)',
    'projects.members': 'Members',
    'projects.typeUsername': 'Type an existing username',
    'projects.dueDate': 'Due date',
    'projects.descriptionOptional': 'Description (optional)',
    'projects.shortDescription': 'Short description',
    'projects.createButton': 'Create',
    'projects.editTitle': 'Edit Project',
    'projects.saveButton': 'Save',
    'projects.deleteTitle': 'Delete Project?',
    'projects.deleteMessage': 'Are you sure you want to delete this project? This action cannot be undone.',
    'projects.createdTitle': 'Projects I created',
    'projects.sharedTitle': 'Projects shared with me',
    'projects.emptyCreated': 'No projects yet. Add one to begin.',
    'projects.emptyShared': 'No shared projects yet.',
    'projects.openBoard': 'Open Board',
    'projects.edit': 'Edit',
    'projects.delete': 'Delete',
    'projects.tasksCount': 'Tasks',
    'projects.due': 'Due',
    'projects.tbd': 'TBD',
    'projects.membersCount': 'Members',
    'projects.memberAdd': 'Add',
    'projects.memberInputError': 'Select a user from suggestions or clear the input.',
    'projects.memberSearchError': 'Could not load users right now. Refresh the page or restart the server.',
    'projects.memberVerifyError': 'Could not verify user. Please try again.',
    'projects.userNotFound': 'User "{user}" does not exist.',
    'projects.tagFallback': 'Project',
    'projects.createFailed': 'Failed to create project',
    'projects.updateFailed': 'Failed to update project',
    'kanban.title': 'Kanban Board',
    'kanban.addTask': 'Add Task',
    'kanban.addColumn': 'Add column',
    'kanban.columnNamePlaceholder': 'Column name',
    'kanban.addColumnButton': 'Add',
    'kanban.addTaskTitle': 'Add Task',
    'kanban.cardTitle': 'Card title',
    'kanban.label': 'Label',
    'kanban.status': 'Status',
    'kanban.dueDate': 'Due date',
    'kanban.descriptionOptional': 'Description (optional)',
    'kanban.descriptionPlaceholder': 'Add a short description',
    'kanban.readMore': 'Read more...',
    'kanban.duePrefix': 'Due',
    'kanban.members': 'Members',
    'kanban.noMembers': 'No members yet.',
    'kanban.membersCount': 'members',
    'kanban.deleteColumnTitle': 'Delete column',
    'kanban.deleteColumnMessage': 'Delete "{column}"? Cards in this column will move to "To Do".',
    'kanban.taskFallback': 'Task',
    'kanban.deleteColumnAria': 'Delete column',
    'kanban.thisColumn': 'this column',
    'task.titlePlaceholder': 'Task title...',
    'task.tags': 'Tags',
    'task.addTagPlaceholder': 'Add a tag',
    'task.dates': 'Dates',
    'task.checklist': 'Checklist',
    'task.priority': 'Priority',
    'task.members': 'Members',
    'task.attachments': 'Attachments',
    'task.priorityLow': 'Low',
    'task.priorityMedium': 'Medium',
    'task.priorityHigh': 'High',
    'task.noCollaborators': 'No collaborators in this project yet.',
    'task.description': 'Description',
    'task.bold': 'Bold',
    'task.underline': 'Underline',
    'task.descriptionPlaceholder': 'Add a detailed description...',
    'task.addAttachment': 'Add',
    'task.attachmentLabelPlaceholder': 'Label (optional)',
    'task.newChecklistName': 'New checklist name',
    'task.addChecklist': 'Add checklist',
    'task.deleteChecklist': 'Delete checklist',
    'task.clickToEdit': 'Click to edit',
    'task.addChecklistItemPlaceholder': 'Add a new item...',
    'task.addItem': '+ Add item',
    'task.assigned': 'Assigned',
    'task.saving': 'Saving...',
    'task.deleteTask': 'Delete task',
    'task.deleteTaskMessage': 'Are you sure you want to delete this task? This action cannot be undone.',
    'task.deleteChecklistItem': 'Delete checklist item',
    'task.deleteChecklistItemMessage': 'Delete "{item}"? This action cannot be undone.',
    'task.deleteAttachmentTitle': 'Delete attachment',
    'task.deleteAttachmentMessage': 'Delete "{attachment}"? This action cannot be undone.',
    'task.deleteChecklistGroupTitle': 'Delete checklist',
    'task.deleteChecklistGroupMessage': 'Delete "{group}"? This will remove all items in it.',
    'task.deleteTaskAria': 'Delete task',
    'wishlist.title': 'Wishlist & Purchases',
    'wishlist.addItem': 'Add item',
    'wishlist.editItemTitle': 'Edit Wishlist Item',
    'wishlist.addItemTitle': 'Add Wishlist Item',
    'wishlist.itemNamePlaceholder': 'Item name',
    'wishlist.pricePlaceholder': 'Price (e.g., $50)',
    'wishlist.saving': 'Saving...',
    'wishlist.update': 'Update',
    'wishlist.add': 'Add',
    'wishlist.wishlistSection': 'Wishlist',
    'wishlist.wishlistEmpty': 'No items in your wishlist yet. Start adding!',
    'wishlist.purchasedSection': 'Purchased',
    'wishlist.purchasedEmpty': 'No purchased items yet.',
    'wishlist.deleteTitle': 'Delete Item',
    'wishlist.deleteMessage': 'Are you sure you want to delete "{item}"? This action cannot be undone.',
    'wishlist.removeImageTitle': 'Remove Image',
    'wishlist.removeImageMessage': 'Are you sure you want to remove this image?',
    'wishlist.thisItem': 'this item',
    'wishlist.removeImage': 'Remove image',
    'wishlist.editItem': 'Edit item',
    'wishlist.markPurchased': 'Mark as purchased',
    'wishlist.deleteItem': 'Delete item',
    'wishlist.purchasedOn': 'Purchased',
    'wishlist.previewAlt': 'Preview',
    'wishlist.imageUploadFailed': 'Item saved but image upload failed',
    'wishlist.saveFailed': 'Failed to save item. Please try again.',
    'upload.invalidType': 'Please upload an image file (JPG, PNG, GIF, or WebP)',
    'upload.tooLarge': 'File size must be less than 5MB',
    'upload.dragDrop': 'Drag and drop your image here or',
    'upload.clickSelect': 'click to select',
    'upload.maxHint': 'Max 5MB (JPG, PNG, GIF, WebP)',
    'feedback.sweetNote': 'Sweet Note',
    'feedback.shareTitle': 'Share feedback',
    'feedback.shareSubtitle': 'Tell me what to add, what to fix, or what feels dreamy.',
    'feedback.tieAlt': 'Bow tie decoration',
    'feedback.nameOnNote': 'Name on note',
    'feedback.anonymous': 'Anonymous',
    'feedback.readEvery': 'We read every message',
    'feedback.beforeSending': 'What to share',
    'feedback.tipOne': 'If you found a bug, choose Bug report and explain what happened.',
    'feedback.tipTwo': 'Share general feedback that reflects your experience and satisfaction.',
    'feedback.tipThree': 'If you want a new feature, choose Feature wish and tell us your idea.',
    'feedback.softNote': 'Clear details help us improve Rosy faster',
    'feedback.namePlaceholder': 'Your name (optional)',
    'feedback.typeFeature': 'Feature wish',
    'feedback.typeBug': 'Bug report',
    'feedback.typeGeneral': 'General feedback',
    'feedback.messagePlaceholder': 'Tell me what you want added or fixed...',
    'feedback.send': 'Send',
    'feedback.thankYou': 'Thank you! I will read it soon.',
    'history.title': 'Weekly Planner History',
    'history.subtitle': 'Browse and reopen past weeks',
    'history.backToPlanner': 'Back to planner',
    'history.loading': 'Loading history...'
  },
  fr: {
    'nav.dashboard': 'Tableau',
    'nav.weekPlanner': 'Semaine',
    'nav.projects': 'Projets',
    'nav.money': 'Budget',
    'nav.notes': 'Notes',
    'nav.wishlist': 'Envies',
    'nav.vision': 'Vision',
    'nav.profile': 'Profil',
    'nav.logout': 'Deconnexion',
    'profile.kicker': 'Ton coin doux',
    'profile.title': 'Studio Profil',
    'profile.subtitle': 'Personnalise ton espace, sauvegarde ton mood et ajoute une jolie photo.',
    'profile.mood': 'Humeur',
    'profile.language': 'Langue',
    'profile.fallbackName': 'Planificatrice douce',
    'profile.fallbackFocus': 'Focus doux, petites victoires',
    'profile.unknownDate': 'Date inconnue',
    'profile.avatarAlt': 'Profil',
    'profile.uploadPhoto': 'Ajouter une photo',
    'profile.removePhoto': 'Supprimer la photo',
    'profile.about': 'A propos de toi',
    'profile.displayName': 'Nom affiche',
    'profile.focus': 'Focus actuel',
    'profile.bio': 'Bio',
    'profile.bioPlaceholder': 'Quelques lignes reveuses sur toi...',
    'profile.mantra': 'Citation / mantra',
    'profile.mantraPlaceholder': 'Une phrase douce pour te porter',
    'profile.birthday': 'Anniversaire',
    'profile.theme': 'Ambiance',
    'profile.themeStrawberry': 'Fraise',
    'profile.themeRoseTea': 'The rose',
    'profile.themeVanilla': 'Vanille',
    'profile.themeMatcha': 'Matcha',
    'profile.langEnglish': 'Anglais',
    'profile.langFrench': 'Francais',
    'profile.langGerman': 'Allemand',
    'profile.save': 'Enregistrer',
    'profile.saved': 'Enregistre !',
    'profile.stats': 'Tes stats',
    'profile.updating': 'Mise a jour...',
    'profile.statTask': 'Tache',
    'profile.statGoal': 'But',
    'profile.statWish': 'Envie',
    'profile.statBuild': 'Projet',
    'profile.tasksCompleted': 'Taches terminees',
    'profile.visionGoals': 'Objectifs vision',
    'profile.wishlistWins': 'Envies achetees',
    'profile.projectsCreated': 'Projets crees',
    'profile.security': 'Securite',
    'profile.currentPassword': 'Mot de passe actuel',
    'profile.newPassword': 'Nouveau mot de passe',
    'profile.confirmPassword': 'Confirmer le mot de passe',
    'profile.passwordPlaceholderMin': 'Au moins 8 caracteres',
    'profile.passwordPlaceholderConfirm': 'Ressaisir le mot de passe',
    'profile.passwordRequired': 'Merci de remplir tous les champs.',
    'profile.passwordTooShort': 'Le mot de passe doit avoir au moins 8 caracteres.',
    'profile.passwordMismatch': 'Le mot de passe et la confirmation ne correspondent pas.',
    'profile.passwordUpdated': 'Mot de passe mis a jour !',
    'profile.passwordFailed': 'Echec de la mise a jour.',
    'profile.updatePassword': 'Mettre a jour',
    'profile.logout': 'Se deconnecter',
    'profile.joined': 'Inscrite le',
    'profile.noteKicker': 'Aujourd\'hui dans ta chambre',
    'profile.noteText': 'Va doucement. Un petit pas compte.',
    'dashboard.welcomeTitle': 'Bon retour ma belle dans ton atelier cosy',
    'dashboard.welcomeSubtitle': 'Aujourd\'hui on mise sur le focus doux. Choisis un projet, bouge une carte, note une victoire.',
    'dashboard.todayPlan': 'Plan du jour',
    'dashboard.moneySnapshot': 'Apercu budget',
    'dashboard.reminders': 'Rappels',
    'dashboard.noTasks': 'Aucune tache. Ajoute la premiere.',
    'dashboard.addTaskPlaceholder': 'Ajouter une tache',
    'dashboard.addTaskButton': 'Ajouter',
    'dashboard.spent': 'Depense',
    'dashboard.saved': 'Epargne',
    'dashboard.moneyTrendAria': 'Tendance budget',
    'dashboard.monthSpent': 'Depense',
    'dashboard.monthSaved': 'Epargne',
    'dashboard.noReminders': 'Aucun rappel pour le moment. Ajoute-en depuis les notes.',
    'dashboard.manageReminders': 'Gerer les rappels',
    'dashboard.deleteTaskTitle': 'Supprimer la tache',
    'dashboard.deleteTaskMessage': 'Voulez-vous supprimer "{task}" ? Cette action est definitive.',
    'dashboard.thisTask': 'cette tache',
    'week.title': 'Planificateur de semaine',
    'week.currentWeek': 'Semaine en cours',
    'week.backToCurrent': 'Retour a la semaine en cours',
    'week.days.monday': 'Lundi',
    'week.days.tuesday': 'Mardi',
    'week.days.wednesday': 'Mercredi',
    'week.days.thursday': 'Jeudi',
    'week.days.friday': 'Vendredi',
    'week.days.saturday': 'Samedi',
    'week.days.sunday': 'Dimanche',
    'week.reflection': 'Bilan hebdo',
    'week.tasksCount': 'taches',
    'week.history': 'Historique',
    'week.noPastWeeks': 'Aucune semaine precedente.',
    'week.current': 'En cours',
    'week.updated': 'Mise a jour',
    'week.viewAllHistory': 'Voir tout l historique',
    'week.doneOf': 'sur',
    'week.doneLabel': 'terminees',
    'week.carryOver': 'Reporter',
    'week.carryOverTitle': 'Deplacer toutes les taches non terminees a demain',
    'week.endOfWeekSummary': 'Resume de fin de semaine',
    'week.dailyFocusGoal': 'Objectif focus du jour',
    'week.focusPlaceholder': 'Victoire principale du jour...',
    'week.dailyTasks': 'Taches du jour',
    'week.taskPlaceholder': 'Ajouter une tache...',
    'week.block.anytime': 'N importe quand',
    'week.block.morning': 'Matin',
    'week.block.afternoon': 'Apres-midi',
    'week.block.evening': 'Soir',
    'week.block.night': 'Nuit',
    'week.priority.high': 'Haut',
    'week.priority.medium': 'Moyen',
    'week.priority.low': 'Bas',
    'week.noTasksDay': 'Aucune tache pour ce jour.',
    'week.reflectionTitle': 'Bilan hebdo',
    'week.reflectionWins': 'Victoires',
    'week.reflectionLessons': 'Lecons',
    'week.reflectionNextWeek': 'Semaine prochaine',
    'week.reflectionWinsPlaceholder': 'Qu est-ce qui a bien marche ?',
    'week.reflectionLessonsPlaceholder': 'Qu as-tu appris ?',
    'week.reflectionNextWeekPlaceholder': 'Sur quoi veux-tu te concentrer la semaine prochaine ?',
    'week.notesTitle': 'Notes',
    'week.notesPlaceholder': 'Ajouter des notes pour ce jour...',
    'week.loading': 'Chargement du planning...',
    'week.deleteTaskTitle': 'Supprimer la tache',
    'week.deleteTaskMessage': 'Voulez-vous supprimer "{task}" ? Cette action est definitive.',
    'week.thisTask': 'cette tache',
    'week.addTaskButton': 'Ajouter',
    'vision.title': 'Tableau de vision',
    'vision.addGoal': 'Ajouter un objectif',
    'vision.addGoalTitle': 'Ajouter un objectif',
    'vision.goalTitlePlaceholder': 'Titre de l objectif',
    'vision.goalDescriptionPlaceholder': 'Decris ta vision...',
    'vision.goalIconPlaceholder': 'Emoji',
    'vision.cancel': 'Annuler',
    'vision.addGoalButton': 'Ajouter',
    'vision.deleteGoalTitle': 'Supprimer l objectif',
    'vision.deleteGoalMessage': 'Voulez-vous supprimer "{goal}" ? Cette action est definitive.',
    'vision.thisGoal': 'cet objectif',
    'vision.markAchieved': 'Marquer atteint',
    'vision.markDone': 'Marquer fait',
    'vision.markUnachieved': 'Marquer non atteint',
    'vision.moveBackToGoals': 'Remettre dans les objectifs',
    'vision.achieved': 'Atteint',
    'vision.archivedTitle': 'Objectifs atteints',
    'vision.archivedSubtitle': 'Un archive doux des objectifs deja accomplis.',
    'vision.emptyCategory': 'Aucun objectif dans cette categorie pour le moment.',
    'vision.emptyArchived': 'Aucun objectif atteint pour le moment.',
    'vision.category.financial.label': 'Financier',
    'vision.category.financial.desc': 'Gestion de l argent, revenus, epargne, dettes, et securite financiere.',
    'vision.category.business.label': 'Business',
    'vision.category.business.desc': 'Evolution de carriere, reussites professionnelles, entrepreneuriat et projets business.',
    'vision.category.relationships.label': 'Relations',
    'vision.category.relationships.desc': 'Relations importantes avec partenaire, amis, famille et entourage.',
    'vision.category.health_fitness.label': 'Sante & Fitness',
    'vision.category.health_fitness.desc': 'Sante physique, forme, habitudes saines et bien-etre global.',
    'vision.category.fun_recreation.label': 'Fun & Loisirs',
    'vision.category.fun_recreation.desc': 'Loisirs, voyages, experiences et activites qui apportent de la joie.',
    'vision.category.personal.label': 'Personnel',
    'vision.category.personal.desc': 'Developpement personnel, education, style de vie et habitudes.',
    'vision.category.contribution.label': 'Contribution',
    'vision.category.contribution.desc': 'Aider les autres, benevolat, dons, et impact positif.',
    'common.cancel': 'Annuler',
    'common.delete': 'Supprimer',
    'common.add': 'Ajouter',
    'common.save': 'Enregistrer',
    'common.update': 'Mettre a jour',
    'common.edit': 'Modifier',
    'common.back': 'Retour',
    'common.loading': 'Chargement...',
    'common.none': 'Aucun',
    'login.createTitle': 'Creer un compte',
    'login.welcomeTitle': 'Bon retour',
    'login.username': 'Nom d utilisateur',
    'login.password': 'Mot de passe',
    'login.emailOptional': 'Email (optionnel)',
    'login.usernamePlaceholder': 'Entrer le nom',
    'login.passwordPlaceholder': 'Entrer le mot de passe',
    'login.emailPlaceholder': 'Entrer l email',
    'login.authFailed': 'Echec de connexion',
    'login.accountCreated': 'Compte cree ! Connecte-toi.',
    'login.pleaseWait': 'Patiente...',
    'login.signUp': 'S inscrire',
    'login.logIn': 'Se connecter',
    'login.haveAccount': 'Deja un compte ? Se connecter',
    'login.noAccount': 'Pas de compte ? S inscrire',
    'landing.headerLogin': 'Se connecter',
    'landing.headerGetStarted': 'Commencer',
    'landing.heroTitle': 'Rosy Workroom',
    'landing.heroSubtitle': 'Un espace doux pour planifier, suivre et fleurir.',
    'landing.heroDescription': 'Un seul coin cosy pour projets, kanban, budgets, notes, objectifs et planning hebdo. Une palette rose douce et un focus calme pour avancer avec plaisir.',
    'landing.heroAlt': 'Sticker fille fraise',
    'landing.heroGetStarted': 'Commencer',
    'landing.heroLogin': 'Se connecter',
    'landing.projectProjectsTitle': 'Projets',
    'landing.projectProjectsDesc': 'Cree et organise tous tes projets au meme endroit. Ajoute des tags, des dates, et suis tout ce sur quoi tu travailles.',
    'landing.projectProjectsLink': 'Voir les projets',
    'landing.projectKanbanTitle': 'Tableau Kanban',
    'landing.projectKanbanDesc': 'Visualise ton flux avec des colonnes personnalisables. Deplace les taches entre A faire, En cours, et Termine.',
    'landing.projectKanbanLink': 'Creer un projet',
    'landing.projectBudgetTitle': 'Budget',
    'landing.projectBudgetDesc': 'Gere ton budget mensuel et tes transactions. Fixe un objectif, note les depenses et revenus.',
    'landing.projectBudgetLink': 'Suivre le budget',
    'landing.projectNotesTitle': 'Notes',
    'landing.projectNotesDesc': 'Capture tes idees et infos importantes dans un carnet propre et simple.',
    'landing.projectNotesLink': 'Prendre des notes',
    'landing.projectVisionTitle': 'Vision Board',
    'landing.projectVisionDesc': 'Definis tes reves et objectifs long terme. Garde une vision claire et motivee.',
    'landing.projectVisionLink': 'Construire la vision',
    'landing.projectWeekTitle': 'Planning hebdo',
    'landing.projectWeekDesc': 'Planifie ta semaine avec intention. Fixe des priorites et organise sans stress.',
    'landing.projectWeekLink': 'Planifier la semaine',
    'landing.reviewsTitle': 'Ce que disent les gens',
    'landing.reviewsSubtitle': 'Les retours doux aident Rosy Workroom a fleurir.',
    'landing.reviewsBadge': 'Note cosy 5.0',
    'landing.review1Quote': 'Le planning hebdo garde mes objectifs doux et realistes. J adore la mise en page.',
    'landing.review1Tag': 'Planning hebdo',
    'landing.review2Quote': 'Le kanban ressemble a un journal, mais avec une structure mignonne.',
    'landing.review2Tag': 'Projets + Kanban',
    'landing.review3Quote': 'Le suivi budget est enfin joli. Je le consulte chaque matin.',
    'landing.review3Tag': 'Suivi budget',
    'landing.footerMade': 'Fait avec amour pour une productivite douce',
    'landing.footerRights': 'Tous droits reserves.',
    'home.title': 'Strawberry Bloom Studio',
    'home.subtitle': 'Un espace doux pour planifier, suivre et rever.',
    'home.description': 'Organise projets, budget, notes et objectifs dans un seul cocon. Suis tes victoires et garde un rythme doux.',
    'home.planProjects': 'Planifier tes projets',
    'home.planWeek': 'Planifier ta semaine',
    'home.trackMoney': 'Suivre ton budget',
    'home.addGoals': 'Ajouter des objectifs',
    'home.takeNotes': 'Prendre des notes',
    'notes.title': 'Notes',
    'notes.newNote': 'Nouvelle note',
    'notes.addNoteTitle': 'Ajouter une note',
    'notes.noteTitlePlaceholder': 'Titre de la note',
    'notes.noteContentPlaceholder': 'Ecris ta note ici...',
    'notes.noteTagsPlaceholder': 'Tags (separes par virgules)',
    'notes.empty': 'Aucune note pour le moment',
    'notes.deleteTitle': 'Supprimer la note',
    'notes.deleteMessage': 'Voulez-vous supprimer "{note}" ? Cette action est definitive.',
    'notes.thisNote': 'cette note',
    'notes.addNoteButton': 'Ajouter',
    'money.title': 'Suivi budget',
    'money.addTransaction': 'Ajouter une transaction',
    'money.addTransactionTitle': 'Ajouter une transaction',
    'money.itemPlaceholder': 'Article',
    'money.categoryPlaceholder': 'Categorie',
    'money.amountPlaceholder': 'Montant',
    'money.addTransactionButton': 'Ajouter',
    'money.setBudgetTitle': 'Definir le budget mensuel',
    'money.budgetPlaceholder': 'Montant du budget',
    'money.saveBudget': 'Enregistrer',
    'money.monthlyOverview': 'Apercu mensuel',
    'money.editBudget': 'Modifier le budget',
    'money.budgetLabel': 'Budget',
    'money.spentLabel': 'Depense',
    'money.savedLabel': 'Epargne',
    'money.topCategory': 'Categorie principale',
    'money.categories': 'Categories',
    'money.budgetUsed': 'du budget utilise',
    'money.recentTransactions': 'Transactions recentes',
    'money.tableDate': 'Date',
    'money.tableItem': 'Article',
    'money.tableCategory': 'Categorie',
    'money.tableAmount': 'Montant',
    'money.noTransactions': 'Aucune transaction pour le moment',
    'money.deleteTitle': 'Supprimer la transaction',
    'money.deleteMessage': 'Voulez-vous supprimer "{tx}" ? Cette action est definitive.',
    'money.thisTransaction': 'cette transaction',
    'projects.title': 'Projets',
    'projects.backToProjects': 'Retour aux projets',
    'projects.addProject': 'Ajouter un projet',
    'projects.createTitle': 'Creer un projet',
    'projects.projectName': 'Nom du projet',
    'projects.projectNamePlaceholder': 'Nom du projet',
    'projects.tags': 'Tags',
    'projects.tagsPlaceholder': 'Tags (separes par virgules)',
    'projects.members': 'Membres',
    'projects.typeUsername': 'Saisir un nom existant',
    'projects.dueDate': 'Date limite',
    'projects.descriptionOptional': 'Description (optionnel)',
    'projects.shortDescription': 'Courte description',
    'projects.createButton': 'Creer',
    'projects.editTitle': 'Modifier le projet',
    'projects.saveButton': 'Enregistrer',
    'projects.deleteTitle': 'Supprimer le projet ?',
    'projects.deleteMessage': 'Voulez-vous supprimer ce projet ? Cette action est definitive.',
    'projects.createdTitle': 'Projets que j ai crees',
    'projects.sharedTitle': 'Projets partages avec moi',
    'projects.emptyCreated': 'Aucun projet. Ajoute-en un pour commencer.',
    'projects.emptyShared': 'Aucun projet partage.',
    'projects.openBoard': 'Ouvrir le tableau',
    'projects.edit': 'Modifier',
    'projects.delete': 'Supprimer',
    'projects.tasksCount': 'Taches',
    'projects.due': 'Echeance',
    'projects.tbd': 'A definir',
    'projects.membersCount': 'Membres',
    'projects.memberAdd': 'Ajouter',
    'projects.memberInputError': 'Choisis un utilisateur dans les suggestions ou vide le champ.',
    'projects.memberSearchError': 'Impossible de charger les utilisateurs. Recharge la page ou relance le serveur.',
    'projects.memberVerifyError': 'Impossible de verifier l utilisateur. Reessaie.',
    'projects.userNotFound': 'Utilisateur "{user}" introuvable.',
    'projects.tagFallback': 'Projet',
    'projects.createFailed': 'Echec de creation du projet',
    'projects.updateFailed': 'Echec de mise a jour du projet',
    'kanban.title': 'Tableau Kanban',
    'kanban.addTask': 'Ajouter une tache',
    'kanban.addColumn': 'Ajouter une colonne',
    'kanban.columnNamePlaceholder': 'Nom de la colonne',
    'kanban.addColumnButton': 'Ajouter',
    'kanban.addTaskTitle': 'Ajouter une tache',
    'kanban.cardTitle': 'Titre de la carte',
    'kanban.label': 'Libelle',
    'kanban.status': 'Statut',
    'kanban.dueDate': 'Date limite',
    'kanban.descriptionOptional': 'Description (optionnel)',
    'kanban.descriptionPlaceholder': 'Ajouter une courte description',
    'kanban.readMore': 'Lire plus...',
    'kanban.duePrefix': 'Echeance',
    'kanban.members': 'Membres',
    'kanban.noMembers': 'Aucun membre pour le moment.',
    'kanban.membersCount': 'membres',
    'kanban.deleteColumnTitle': 'Supprimer la colonne',
    'kanban.deleteColumnMessage': 'Supprimer "{column}" ? Les cartes seront deplacees vers "To Do".',
    'kanban.taskFallback': 'Tache',
    'kanban.deleteColumnAria': 'Supprimer la colonne',
    'kanban.thisColumn': 'cette colonne',
    'task.titlePlaceholder': 'Titre de la tache...',
    'task.tags': 'Tags',
    'task.addTagPlaceholder': 'Ajouter un tag',
    'task.dates': 'Dates',
    'task.checklist': 'Checklist',
    'task.priority': 'Priorite',
    'task.members': 'Membres',
    'task.attachments': 'Pieces jointes',
    'task.priorityLow': 'Bas',
    'task.priorityMedium': 'Moyen',
    'task.priorityHigh': 'Haut',
    'task.noCollaborators': 'Aucun collaborateur dans ce projet.',
    'task.description': 'Description',
    'task.bold': 'Gras',
    'task.underline': 'Souligne',
    'task.descriptionPlaceholder': 'Ajouter une description detaillee...',
    'task.addAttachment': 'Ajouter',
    'task.attachmentLabelPlaceholder': 'Libelle (optionnel)',
    'task.newChecklistName': 'Nom de la checklist',
    'task.addChecklist': 'Ajouter une checklist',
    'task.deleteChecklist': 'Supprimer la checklist',
    'task.clickToEdit': 'Cliquer pour modifier',
    'task.addChecklistItemPlaceholder': 'Ajouter un element...',
    'task.addItem': '+ Ajouter un element',
    'task.assigned': 'Assigne',
    'task.saving': 'Enregistrement...',
    'task.deleteTask': 'Supprimer la tache',
    'task.deleteTaskMessage': 'Voulez-vous supprimer cette tache ? Cette action est definitive.',
    'task.deleteChecklistItem': 'Supprimer un element',
    'task.deleteChecklistItemMessage': 'Supprimer "{item}" ? Cette action est definitive.',
    'task.deleteAttachmentTitle': 'Supprimer la piece jointe',
    'task.deleteAttachmentMessage': 'Supprimer "{attachment}" ? Cette action est definitive.',
    'task.deleteChecklistGroupTitle': 'Supprimer la checklist',
    'task.deleteChecklistGroupMessage': 'Supprimer "{group}" ? Tous les elements seront supprimes.',
    'task.deleteTaskAria': 'Supprimer la tache',
    'wishlist.title': 'Wishlist & Achats',
    'wishlist.addItem': 'Ajouter un item',
    'wishlist.editItemTitle': 'Modifier un item',
    'wishlist.addItemTitle': 'Ajouter un item',
    'wishlist.itemNamePlaceholder': 'Nom de l item',
    'wishlist.pricePlaceholder': 'Prix (ex: 50 MAD)',
    'wishlist.saving': 'Enregistrement...',
    'wishlist.update': 'Mettre a jour',
    'wishlist.add': 'Ajouter',
    'wishlist.wishlistSection': 'Wishlist',
    'wishlist.wishlistEmpty': 'Aucun item pour le moment. Commence a ajouter !',
    'wishlist.purchasedSection': 'Achats',
    'wishlist.purchasedEmpty': 'Aucun achat pour le moment.',
    'wishlist.deleteTitle': 'Supprimer l item',
    'wishlist.deleteMessage': 'Voulez-vous supprimer "{item}" ? Cette action est definitive.',
    'wishlist.removeImageTitle': 'Supprimer l image',
    'wishlist.removeImageMessage': 'Voulez-vous supprimer cette image ?',
    'wishlist.thisItem': 'cet item',
    'wishlist.removeImage': 'Supprimer l image',
    'wishlist.editItem': 'Modifier l item',
    'wishlist.markPurchased': 'Marquer comme achete',
    'wishlist.deleteItem': 'Supprimer l item',
    'wishlist.purchasedOn': 'Achete',
    'wishlist.previewAlt': 'Apercu',
    'wishlist.imageUploadFailed': 'Item enregistre mais image non envoyee',
    'wishlist.saveFailed': 'Echec de l enregistrement. Reessaie.',
    'upload.invalidType': 'Merci de choisir une image (JPG, PNG, GIF, ou WebP)',
    'upload.tooLarge': 'La taille doit etre inferieure a 5MB',
    'upload.dragDrop': 'Glisse et depose ton image ici ou',
    'upload.clickSelect': 'clique pour choisir',
    'upload.maxHint': 'Max 5MB (JPG, PNG, GIF, WebP)',
    'feedback.sweetNote': 'Note douce',
    'feedback.shareTitle': 'Partager un retour',
    'feedback.shareSubtitle': 'Dis-moi quoi ajouter, corriger, ou rendre plus doux.',
    'feedback.tieAlt': 'Decoration noeud',
    'feedback.nameOnNote': 'Nom sur la note',
    'feedback.anonymous': 'Anonyme',
    'feedback.readEvery': 'On lit chaque message',
    'feedback.beforeSending': 'Que partager',
    'feedback.tipOne': 'Si tu trouves un bug, choisis Signaler un bug et explique ce qui s est passe.',
    'feedback.tipTwo': 'Partage un retour general sur ton experience et ton niveau de satisfaction.',
    'feedback.tipThree': 'Si tu veux une nouvelle fonctionnalite, choisis Souhait de feature et decris ton idee.',
    'feedback.softNote': 'Des details clairs nous aident a ameliorer Rosy plus vite',
    'feedback.namePlaceholder': 'Ton nom (optionnel)',
    'feedback.typeFeature': 'Souhait de feature',
    'feedback.typeBug': 'Signaler un bug',
    'feedback.typeGeneral': 'Retour general',
    'feedback.messagePlaceholder': 'Dis ce que tu veux ajouter ou corriger...',
    'feedback.send': 'Envoyer',
    'feedback.thankYou': 'Merci ! Je le lirai bientot.',
    'history.title': 'Historique du planning',
    'history.subtitle': 'Parcourir et rouvrir les semaines passees',
    'history.backToPlanner': 'Retour au planner',
    'history.loading': 'Chargement de l historique...'
  },
  de: {
    'nav.dashboard': 'Dashboard',
    'nav.weekPlanner': 'Wochenplan',
    'nav.projects': 'Projekte',
    'nav.money': 'Budget',
    'nav.notes': 'Notizen',
    'nav.wishlist': 'Wunschliste',
    'nav.vision': 'Vision',
    'nav.profile': 'Profil',
    'nav.logout': 'Abmelden',
    'profile.kicker': 'Dein sanfter Ort',
    'profile.title': 'Profil Studio',
    'profile.subtitle': 'Gestalte deinen Raum, speichere dein Mood und lade ein suesses Foto hoch.',
    'profile.mood': 'Stimmung',
    'profile.language': 'Sprache',
    'profile.fallbackName': 'Sanfte Planerin',
    'profile.fallbackFocus': 'Sanfter Fokus, kleine Siege',
    'profile.unknownDate': 'Unbekanntes Datum',
    'profile.avatarAlt': 'Profil',
    'profile.uploadPhoto': 'Foto hochladen',
    'profile.removePhoto': 'Foto entfernen',
    'profile.about': 'Ueber dich',
    'profile.displayName': 'Anzeigename',
    'profile.focus': 'Aktueller Fokus',
    'profile.bio': 'Bio',
    'profile.bioPlaceholder': 'Ein paar traumerische Zeilen ueber dich...',
    'profile.mantra': 'Zitat / Mantra',
    'profile.mantraPlaceholder': 'Ein sanfter Satz, der dich traegt',
    'profile.birthday': 'Geburtstag',
    'profile.theme': 'Stimmung',
    'profile.themeStrawberry': 'Erdbeere',
    'profile.themeRoseTea': 'Rosentee',
    'profile.themeVanilla': 'Vanille',
    'profile.themeMatcha': 'Matcha',
    'profile.langEnglish': 'Englisch',
    'profile.langFrench': 'Franzoesisch',
    'profile.langGerman': 'Deutsch',
    'profile.save': 'Speichern',
    'profile.saved': 'Gespeichert!',
    'profile.stats': 'Deine Stats',
    'profile.updating': 'Aktualisiere...',
    'profile.statTask': 'Aufgabe',
    'profile.statGoal': 'Ziel',
    'profile.statWish': 'Wunsch',
    'profile.statBuild': 'Projekt',
    'profile.tasksCompleted': 'Aufgaben erledigt',
    'profile.visionGoals': 'Vision-Ziele',
    'profile.goalsAchieved': 'Erreichte Ziele',
    'profile.wishlistWins': 'Wuensche gekauft',
    'profile.projectsCreated': 'Projekte erstellt',
    'profile.security': 'Sicherheit',
    'profile.currentPassword': 'Aktuelles Passwort',
    'profile.newPassword': 'Neues Passwort',
    'profile.confirmPassword': 'Passwort bestaetigen',
    'profile.passwordPlaceholderMin': 'Mindestens 8 Zeichen',
    'profile.passwordPlaceholderConfirm': 'Passwort erneut eingeben',
    'profile.passwordRequired': 'Bitte alle Passwortfelder ausfuellen.',
    'profile.passwordTooShort': 'Das neue Passwort muss mindestens 8 Zeichen haben.',
    'profile.passwordMismatch': 'Passwort und Bestaetigung stimmen nicht ueberein.',
    'profile.passwordUpdated': 'Passwort aktualisiert!',
    'profile.passwordFailed': 'Passwort-Update fehlgeschlagen.',
    'profile.updatePassword': 'Aktualisieren',
    'profile.logout': 'Abmelden',
    'profile.joined': 'Beigetreten am',
    'profile.noteKicker': 'Heute in deinem Zimmer',
    'profile.noteText': 'Ganz sanft. Ein kleiner Schritt zaehlt.',
    'dashboard.welcomeTitle': 'Willkommen zurueck, Liebling, in deinem gemuetlichen Workroom',
    'dashboard.welcomeSubtitle': 'Heute geht es um sanften Fokus. Waehle ein Projekt, bewege eine Karte und notiere einen Sieg.',
    'dashboard.todayPlan': 'Tagesplan',
    'dashboard.moneySnapshot': 'Geldueberblick',
    'dashboard.reminders': 'Erinnerungen',
    'dashboard.noTasks': 'Noch keine Aufgaben. Fuege die erste hinzu.',
    'dashboard.addTaskPlaceholder': 'Aufgabe hinzufuegen',
    'dashboard.addTaskButton': 'Hinzufuegen',
    'dashboard.spent': 'Ausgegeben',
    'dashboard.saved': 'Gespart',
    'dashboard.moneyTrendAria': 'Geldtrend',
    'dashboard.monthSpent': 'Ausgegeben',
    'dashboard.monthSaved': 'Gespart',
    'dashboard.noReminders': 'Noch keine Erinnerungen. Fuege eine aus den Notizen hinzu.',
    'dashboard.manageReminders': 'Erinnerungen verwalten',
    'dashboard.deleteTaskTitle': 'Aufgabe loeschen',
    'dashboard.deleteTaskMessage': 'Moechtest du "{task}" loeschen? Diese Aktion kann nicht rueckgaengig gemacht werden.',
    'dashboard.thisTask': 'diese Aufgabe',
    'week.title': 'Wochenplaner',
    'week.currentWeek': 'Aktuelle Woche',
    'week.backToCurrent': 'Zurueck zur aktuellen Woche',
    'week.days.monday': 'Montag',
    'week.days.tuesday': 'Dienstag',
    'week.days.wednesday': 'Mittwoch',
    'week.days.thursday': 'Donnerstag',
    'week.days.friday': 'Freitag',
    'week.days.saturday': 'Samstag',
    'week.days.sunday': 'Sonntag',
    'week.reflection': 'Wochenrueckblick',
    'week.tasksCount': 'Aufgaben',
    'week.history': 'Verlauf',
    'week.noPastWeeks': 'Noch keine frueheren Wochen.',
    'week.current': 'Aktuell',
    'week.updated': 'Aktualisiert',
    'week.viewAllHistory': 'Gesamten Verlauf ansehen',
    'week.doneOf': 'von',
    'week.doneLabel': 'erledigt',
    'week.carryOver': 'Verschieben',
    'week.carryOverTitle': 'Alle unerledigten Aufgaben auf morgen verschieben',
    'week.endOfWeekSummary': 'Zusammenfassung zum Wochenende',
    'week.dailyFocusGoal': 'Tagesfokus Ziel',
    'week.focusPlaceholder': 'Hauptgewinn fuer heute...',
    'week.dailyTasks': 'Tagesaufgaben',
    'week.taskPlaceholder': 'Aufgabe hinzufuegen...',
    'week.block.anytime': 'Jederzeit',
    'week.block.morning': 'Morgen',
    'week.block.afternoon': 'Nachmittag',
    'week.block.evening': 'Abend',
    'week.block.night': 'Nacht',
    'week.priority.high': 'Hoch',
    'week.priority.medium': 'Mittel',
    'week.priority.low': 'Niedrig',
    'week.noTasksDay': 'Noch keine Aufgaben fuer diesen Tag.',
    'week.reflectionTitle': 'Wochenrueckblick',
    'week.reflectionWins': 'Erfolge',
    'week.reflectionLessons': 'Lernmomente',
    'week.reflectionNextWeek': 'Naechste Woche',
    'week.reflectionWinsPlaceholder': 'Was lief diese Woche gut?',
    'week.reflectionLessonsPlaceholder': 'Was hast du gelernt?',
    'week.reflectionNextWeekPlaceholder': 'Worauf moechtest du dich naechste Woche konzentrieren?',
    'week.notesTitle': 'Notizen',
    'week.notesPlaceholder': 'Notizen fuer diesen Tag hinzufuegen...',
    'week.loading': 'Planer wird geladen...',
    'week.deleteTaskTitle': 'Aufgabe loeschen',
    'week.deleteTaskMessage': 'Moechtest du "{task}" loeschen? Diese Aktion kann nicht rueckgaengig gemacht werden.',
    'week.thisTask': 'diese Aufgabe',
    'week.addTaskButton': 'Hinzufuegen',
    'vision.title': 'Vision Board',
    'vision.addGoal': 'Ziel hinzufuegen',
    'vision.addGoalTitle': 'Vision Ziel hinzufuegen',
    'vision.goalTitlePlaceholder': 'Zieltitel',
    'vision.goalDescriptionPlaceholder': 'Beschreibe deine Vision...',
    'vision.goalIconPlaceholder': 'Emoji',
    'vision.cancel': 'Abbrechen',
    'vision.addGoalButton': 'Ziel hinzufuegen',
    'vision.deleteGoalTitle': 'Ziel loeschen',
    'vision.deleteGoalMessage': 'Moechtest du "{goal}" loeschen? Diese Aktion kann nicht rueckgaengig gemacht werden.',
    'vision.thisGoal': 'dieses Ziel',
    'vision.markAchieved': 'Als erreicht markieren',
    'vision.markDone': 'Als erledigt markieren',
    'vision.markUnachieved': 'Als nicht erreicht markieren',
    'vision.moveBackToGoals': 'Zurueck zu Zielen',
    'vision.achieved': 'Erreicht',
    'vision.archivedTitle': 'Erreichte Ziele',
    'vision.archivedSubtitle': 'Ein sanftes Archiv deiner bereits erledigten Ziele.',
    'vision.emptyCategory': 'Noch keine Ziele in dieser Kategorie.',
    'vision.emptyArchived': 'Noch keine erreichten Ziele.',
    'vision.category.financial.label': 'Finanzen',
    'vision.category.financial.desc': 'Geldmanagement, Einkommen, Sparen, Schuldenabbau und finanzielle Sicherheit.',
    'vision.category.business.label': 'Business',
    'vision.category.business.desc': 'Karrierewachstum, berufliche Erfolge, Unternehmertum und Business-Projekte.',
    'vision.category.relationships.label': 'Beziehungen',
    'vision.category.relationships.desc': 'Bedeutungsvolle Verbindungen zu Partner, Familie, Freunden und Umfeld.',
    'vision.category.health_fitness.label': 'Gesundheit & Fitness',
    'vision.category.health_fitness.desc': 'Koerperliche Gesundheit, Fitness, gesunde Gewohnheiten und Wohlbefinden.',
    'vision.category.fun_recreation.label': 'Spass & Freizeit',
    'vision.category.fun_recreation.desc': 'Hobbys, Reisen, Erlebnisse und Dinge, die Freude bringen.',
    'vision.category.personal.label': 'Persoenlich',
    'vision.category.personal.desc': 'Selbstentwicklung, Bildung, Gewohnheiten, Lebensstil und persoenliche Verbesserungen.',
    'vision.category.contribution.label': 'Beitrag',
    'vision.category.contribution.desc': 'Anderen helfen, Ehrenamt, Spenden und positiver Einfluss.',
    'common.cancel': 'Abbrechen',
    'common.delete': 'Loeschen',
    'common.add': 'Hinzufuegen',
    'common.save': 'Speichern',
    'common.update': 'Aktualisieren',
    'common.edit': 'Bearbeiten',
    'common.back': 'Zurueck',
    'common.loading': 'Laedt...',
    'common.none': 'Keine',
    'login.createTitle': 'Konto erstellen',
    'login.welcomeTitle': 'Willkommen zurueck',
    'login.username': 'Benutzername',
    'login.password': 'Passwort',
    'login.emailOptional': 'Email (optional)',
    'login.usernamePlaceholder': 'Benutzernamen eingeben',
    'login.passwordPlaceholder': 'Passwort eingeben',
    'login.emailPlaceholder': 'Email eingeben',
    'login.authFailed': 'Anmeldung fehlgeschlagen',
    'login.accountCreated': 'Konto erstellt! Bitte einloggen.',
    'login.pleaseWait': 'Bitte warten...',
    'login.signUp': 'Registrieren',
    'login.logIn': 'Einloggen',
    'login.haveAccount': 'Schon ein Konto? Einloggen',
    'login.noAccount': 'Noch kein Konto? Registrieren',
    'landing.headerLogin': 'Einloggen',
    'landing.headerGetStarted': 'Loslegen',
    'landing.heroTitle': 'Rosy Workroom',
    'landing.heroSubtitle': 'Ein sanfter Raum zum Planen, Tracken und Bluehen.',
    'landing.heroDescription': 'Ein gemuetlicher Ort fuer Projekte, Kanban, Budget, Notizen, Ziele und Wochenplanung. Sanftes Rosa und ruhiger Fokus fuer schoene Fortschritte.',
    'landing.heroAlt': 'Erdbeer Maedchen Sticker',
    'landing.heroGetStarted': 'Loslegen',
    'landing.heroLogin': 'Einloggen',
    'landing.projectProjectsTitle': 'Projekte',
    'landing.projectProjectsDesc': 'Erstelle und organisiere all deine Projekte an einem Ort. Tags, Termine und klare Uebersicht.',
    'landing.projectProjectsLink': 'Projekte ansehen',
    'landing.projectKanbanTitle': 'Kanban Board',
    'landing.projectKanbanDesc': 'Visualisiere deinen Workflow mit anpassbaren Spalten. Schiebe Aufgaben durch To Do, In Progress und Done.',
    'landing.projectKanbanLink': 'Projekt erstellen',
    'landing.projectBudgetTitle': 'Budget Tracker',
    'landing.projectBudgetDesc': 'Verwalte dein Budget mit Monatszielen und Transaktionen. Behalte Einnahmen und Ausgaben im Blick.',
    'landing.projectBudgetLink': 'Budget verfolgen',
    'landing.projectNotesTitle': 'Notizen',
    'landing.projectNotesDesc': 'Halte Gedanken und Ideen in einem klaren Notizbuch fest.',
    'landing.projectNotesLink': 'Notizen machen',
    'landing.projectVisionTitle': 'Vision Board',
    'landing.projectVisionDesc': 'Definiere Traeume und langfristige Ziele. Bleib inspiriert und motiviert.',
    'landing.projectVisionLink': 'Vision bauen',
    'landing.projectWeekTitle': 'Wochenplan',
    'landing.projectWeekDesc': 'Plane deine Woche mit Klarheit. Setze Prioritaeten und bleib entspannt organisiert.',
    'landing.projectWeekLink': 'Woche planen',
    'landing.reviewsTitle': 'Was andere sagen',
    'landing.reviewsSubtitle': 'Sanftes Feedback laesst Rosy Workroom bluehen.',
    'landing.reviewsBadge': '5.0 cozy rating',
    'landing.review1Quote': 'Der Wochenplan haelt meine Ziele weich und realistisch. Ich liebe das Layout.',
    'landing.review1Tag': 'Wochenplan',
    'landing.review2Quote': 'Das Kanban Board fuehlt sich an wie Journaling mit Struktur.',
    'landing.review2Tag': 'Projekte + Kanban',
    'landing.review3Quote': 'Budget Tracking ist endlich schoen. Ich schaue jeden Morgen rein.',
    'landing.review3Tag': 'Budget',
    'landing.footerMade': 'Mit Liebe fuer sanfte Produktivitaet',
    'landing.footerRights': 'Alle Rechte vorbehalten.',
    'home.title': 'Strawberry Bloom Studio',
    'home.subtitle': 'Ein suesser Raum fuer Planung, Tracking und Fokus.',
    'home.description': 'Organisiere Projekte, Budget, Notizen und Ziele an einem Ort. Sanfte Prioritaeten und klare Tage.',
    'home.planProjects': 'Projekte planen',
    'home.planWeek': 'Woche planen',
    'home.trackMoney': 'Budget verfolgen',
    'home.addGoals': 'Ziele hinzufuegen',
    'home.takeNotes': 'Notizen machen',
    'notes.title': 'Notizen',
    'notes.newNote': 'Neue Notiz',
    'notes.addNoteTitle': 'Notiz hinzufuegen',
    'notes.noteTitlePlaceholder': 'Notiz Titel',
    'notes.noteContentPlaceholder': 'Schreibe deine Notiz...',
    'notes.noteTagsPlaceholder': 'Tags (durch Kommas getrennt)',
    'notes.empty': 'Noch keine Notizen',
    'notes.deleteTitle': 'Notiz loeschen',
    'notes.deleteMessage': 'Moechtest du "{note}" loeschen? Diese Aktion kann nicht rueckgaengig gemacht werden.',
    'notes.thisNote': 'diese Notiz',
    'notes.addNoteButton': 'Hinzufuegen',
    'money.title': 'Budget Tracker',
    'money.addTransaction': 'Transaktion hinzufuegen',
    'money.addTransactionTitle': 'Transaktion hinzufuegen',
    'money.itemPlaceholder': 'Posten',
    'money.categoryPlaceholder': 'Kategorie',
    'money.amountPlaceholder': 'Betrag',
    'money.addTransactionButton': 'Hinzufuegen',
    'money.setBudgetTitle': 'Monatsbudget setzen',
    'money.budgetPlaceholder': 'Budget Betrag',
    'money.saveBudget': 'Budget speichern',
    'money.monthlyOverview': 'Monatsuebersicht',
    'money.editBudget': 'Budget bearbeiten',
    'money.budgetLabel': 'Budget',
    'money.spentLabel': 'Ausgegeben',
    'money.savedLabel': 'Gespart',
    'money.topCategory': 'Top Kategorie',
    'money.categories': 'Kategorien',
    'money.budgetUsed': 'des Budgets genutzt',
    'money.recentTransactions': 'Letzte Transaktionen',
    'money.tableDate': 'Datum',
    'money.tableItem': 'Posten',
    'money.tableCategory': 'Kategorie',
    'money.tableAmount': 'Betrag',
    'money.noTransactions': 'Noch keine Transaktionen',
    'money.deleteTitle': 'Transaktion loeschen',
    'money.deleteMessage': 'Moechtest du "{tx}" loeschen? Diese Aktion kann nicht rueckgaengig gemacht werden.',
    'money.thisTransaction': 'diese Transaktion',
    'projects.title': 'Projekte',
    'projects.backToProjects': 'Zurueck zu Projekten',
    'projects.addProject': 'Projekt hinzufuegen',
    'projects.createTitle': 'Projekt erstellen',
    'projects.projectName': 'Projektname',
    'projects.projectNamePlaceholder': 'Projektname',
    'projects.tags': 'Tags',
    'projects.tagsPlaceholder': 'Tags (durch Kommas getrennt)',
    'projects.members': 'Mitglieder',
    'projects.typeUsername': 'Existierenden Benutzernamen eingeben',
    'projects.dueDate': 'Faelligkeit',
    'projects.descriptionOptional': 'Beschreibung (optional)',
    'projects.shortDescription': 'Kurze Beschreibung',
    'projects.createButton': 'Erstellen',
    'projects.editTitle': 'Projekt bearbeiten',
    'projects.saveButton': 'Speichern',
    'projects.deleteTitle': 'Projekt loeschen?',
    'projects.deleteMessage': 'Moechtest du dieses Projekt loeschen? Diese Aktion kann nicht rueckgaengig gemacht werden.',
    'projects.createdTitle': 'Projekte, die ich erstellt habe',
    'projects.sharedTitle': 'Mit mir geteilte Projekte',
    'projects.emptyCreated': 'Noch keine Projekte. Fuege eins hinzu.',
    'projects.emptyShared': 'Noch keine geteilten Projekte.',
    'projects.openBoard': 'Board oeffnen',
    'projects.edit': 'Bearbeiten',
    'projects.delete': 'Loeschen',
    'projects.tasksCount': 'Aufgaben',
    'projects.due': 'Faellig',
    'projects.tbd': 'Offen',
    'projects.membersCount': 'Mitglieder',
    'projects.memberAdd': 'Hinzufuegen',
    'projects.memberInputError': 'Waehle einen Nutzer aus oder leere das Feld.',
    'projects.memberSearchError': 'Nutzer konnten nicht geladen werden. Seite neu laden oder Server starten.',
    'projects.memberVerifyError': 'Nutzer konnte nicht verifiziert werden. Bitte erneut versuchen.',
    'projects.userNotFound': 'Benutzer "{user}" existiert nicht.',
    'projects.tagFallback': 'Projekt',
    'projects.createFailed': 'Projekt konnte nicht erstellt werden',
    'projects.updateFailed': 'Projekt konnte nicht aktualisiert werden',
    'kanban.title': 'Kanban Board',
    'kanban.addTask': 'Aufgabe hinzufuegen',
    'kanban.addColumn': 'Spalte hinzufuegen',
    'kanban.columnNamePlaceholder': 'Spaltenname',
    'kanban.addColumnButton': 'Hinzufuegen',
    'kanban.addTaskTitle': 'Aufgabe hinzufuegen',
    'kanban.cardTitle': 'Kartentitel',
    'kanban.label': 'Label',
    'kanban.status': 'Status',
    'kanban.dueDate': 'Faelligkeit',
    'kanban.descriptionOptional': 'Beschreibung (optional)',
    'kanban.descriptionPlaceholder': 'Kurze Beschreibung hinzufuegen',
    'kanban.readMore': 'Mehr lesen...',
    'kanban.duePrefix': 'Faellig',
    'kanban.members': 'Mitglieder',
    'kanban.noMembers': 'Noch keine Mitglieder.',
    'kanban.membersCount': 'Mitglieder',
    'kanban.deleteColumnTitle': 'Spalte loeschen',
    'kanban.deleteColumnMessage': '"{column}" loeschen? Karten werden nach "To Do" verschoben.',
    'kanban.taskFallback': 'Aufgabe',
    'kanban.deleteColumnAria': 'Spalte loeschen',
    'kanban.thisColumn': 'diese Spalte',
    'task.titlePlaceholder': 'Aufgabentitel...',
    'task.tags': 'Tags',
    'task.addTagPlaceholder': 'Tag hinzufuegen',
    'task.dates': 'Daten',
    'task.checklist': 'Checklist',
    'task.priority': 'Prioritaet',
    'task.members': 'Mitglieder',
    'task.attachments': 'Anhaenge',
    'task.priorityLow': 'Niedrig',
    'task.priorityMedium': 'Mittel',
    'task.priorityHigh': 'Hoch',
    'task.noCollaborators': 'Noch keine Mitarbeiter in diesem Projekt.',
    'task.description': 'Beschreibung',
    'task.bold': 'Fett',
    'task.underline': 'Unterstrichen',
    'task.descriptionPlaceholder': 'Eine detaillierte Beschreibung hinzufuegen...',
    'task.addAttachment': 'Hinzufuegen',
    'task.attachmentLabelPlaceholder': 'Label (optional)',
    'task.newChecklistName': 'Neuer Checklist Name',
    'task.addChecklist': 'Checklist hinzufuegen',
    'task.deleteChecklist': 'Checklist loeschen',
    'task.clickToEdit': 'Zum Bearbeiten klicken',
    'task.addChecklistItemPlaceholder': 'Neues Element hinzufuegen...',
    'task.addItem': '+ Element hinzufuegen',
    'task.assigned': 'Zugewiesen',
    'task.saving': 'Speichert...',
    'task.deleteTask': 'Aufgabe loeschen',
    'task.deleteTaskMessage': 'Moechtest du diese Aufgabe loeschen? Diese Aktion kann nicht rueckgaengig gemacht werden.',
    'task.deleteChecklistItem': 'Checklist Element loeschen',
    'task.deleteChecklistItemMessage': '"{item}" loeschen? Diese Aktion kann nicht rueckgaengig gemacht werden.',
    'task.deleteAttachmentTitle': 'Anhang loeschen',
    'task.deleteAttachmentMessage': '"{attachment}" loeschen? Diese Aktion kann nicht rueckgaengig gemacht werden.',
    'task.deleteChecklistGroupTitle': 'Checklist loeschen',
    'task.deleteChecklistGroupMessage': '"{group}" loeschen? Alle Elemente werden entfernt.',
    'task.deleteTaskAria': 'Aufgabe loeschen',
    'wishlist.title': 'Wunschliste & Kaeufe',
    'wishlist.addItem': 'Artikel hinzufuegen',
    'wishlist.editItemTitle': 'Artikel bearbeiten',
    'wishlist.addItemTitle': 'Artikel hinzufuegen',
    'wishlist.itemNamePlaceholder': 'Artikelname',
    'wishlist.pricePlaceholder': 'Preis (z.B. 50 MAD)',
    'wishlist.saving': 'Speichert...',
    'wishlist.update': 'Aktualisieren',
    'wishlist.add': 'Hinzufuegen',
    'wishlist.wishlistSection': 'Wunschliste',
    'wishlist.wishlistEmpty': 'Noch keine Wunschliste Eintraege. Fuege welche hinzu!',
    'wishlist.purchasedSection': 'Gekauft',
    'wishlist.purchasedEmpty': 'Noch keine Kaeufe.',
    'wishlist.deleteTitle': 'Artikel loeschen',
    'wishlist.deleteMessage': 'Moechtest du "{item}" loeschen? Diese Aktion kann nicht rueckgaengig gemacht werden.',
    'wishlist.removeImageTitle': 'Bild entfernen',
    'wishlist.removeImageMessage': 'Moechtest du dieses Bild entfernen?',
    'wishlist.thisItem': 'diesen Artikel',
    'wishlist.removeImage': 'Bild entfernen',
    'wishlist.editItem': 'Artikel bearbeiten',
    'wishlist.markPurchased': 'Als gekauft markieren',
    'wishlist.deleteItem': 'Artikel loeschen',
    'wishlist.purchasedOn': 'Gekauft',
    'wishlist.previewAlt': 'Vorschau',
    'wishlist.imageUploadFailed': 'Artikel gespeichert, aber Bild Upload fehlgeschlagen',
    'wishlist.saveFailed': 'Artikel konnte nicht gespeichert werden. Bitte erneut versuchen.',
    'upload.invalidType': 'Bitte eine Bilddatei hochladen (JPG, PNG, GIF, oder WebP)',
    'upload.tooLarge': 'Datei darf nicht groesser als 5MB sein',
    'upload.dragDrop': 'Bild hierher ziehen oder',
    'upload.clickSelect': 'klicken um auszuwaehlen',
    'upload.maxHint': 'Max 5MB (JPG, PNG, GIF, WebP)',
    'feedback.sweetNote': 'Suesser Zettel',
    'feedback.shareTitle': 'Feedback teilen',
    'feedback.shareSubtitle': 'Sag mir, was ich hinzufuegen, fixen oder verschoenern soll.',
    'feedback.tieAlt': 'Fliege Dekoration',
    'feedback.nameOnNote': 'Name auf dem Zettel',
    'feedback.anonymous': 'Anonym',
    'feedback.readEvery': 'Wir lesen jede Nachricht',
    'feedback.beforeSending': 'Was du teilen kannst',
    'feedback.tipOne': 'Wenn du einen Bug findest, waehle Bug melden und beschreibe genau, was passiert ist.',
    'feedback.tipTwo': 'Teile allgemeines Feedback zu deiner Erfahrung und Zufriedenheit mit der App.',
    'feedback.tipThree': 'Wenn du eine neue Funktion willst, waehle Feature Wunsch und beschreibe deine Idee.',
    'feedback.softNote': 'Klare Details helfen uns, Rosy schneller zu verbessern',
    'feedback.namePlaceholder': 'Dein Name (optional)',
    'feedback.typeFeature': 'Feature Wunsch',
    'feedback.typeBug': 'Bug melden',
    'feedback.typeGeneral': 'Allgemeines Feedback',
    'feedback.messagePlaceholder': 'Sag, was du hinzugefuegt oder behoben haben willst...',
    'feedback.send': 'Senden',
    'feedback.thankYou': 'Danke! Ich lese es bald.',
    'history.title': 'Wochenplan Verlauf',
    'history.subtitle': 'Vergangene Wochen ansehen',
    'history.backToPlanner': 'Zurueck zum Planer',
    'history.loading': 'Verlauf wird geladen...'
  }
}

function resolveLanguageKey(value) {
  if (!value) return 'en'
  const lower = value.toLowerCase()
  if (lower.startsWith('fr')) return 'fr'
  if (lower.startsWith('de') || lower.startsWith('ger') || lower.startsWith('deu') || lower.includes('deutsch')) return 'de'
  return 'en'
}

const LanguageContext = createContext(null)

export function LanguageProvider({ initialLanguage, children }) {
  const [language, setLanguage] = useState(() => {
    const stored = localStorage.getItem('appLanguage')
    return stored || initialLanguage || 'English'
  })

  useEffect(() => {
    const stored = localStorage.getItem('appLanguage')
    if (!stored && initialLanguage && initialLanguage !== language) {
      setLanguage(initialLanguage)
    }
  }, [initialLanguage])

  useEffect(() => {
    if (language) {
      localStorage.setItem('appLanguage', language)
    }
  }, [language])

  const value = useMemo(() => {
    const langKey = resolveLanguageKey(language)
    const dictionary = translations[langKey] || translations.en
    const t = (key) => dictionary[key] || key
    return { language, setLanguage, t, langKey }
  }, [language])

  return (
    <LanguageContext.Provider value={value}>
      {children}
    </LanguageContext.Provider>
  )
}

export function useLanguage() {
  const context = useContext(LanguageContext)
  if (!context) {
    throw new Error('useLanguage must be used within LanguageProvider')
  }
  return context
}
